[project]
name = "stripe-ticket-printer"
revision = "1.0"

[profiles.default]
STRIPE_SECRET_KEY = { description = "Stripe API key" }

[profiles.production]
STRIPE_SECRET_KEY = { description = "Stripe API key", required = true }
